stages:
  - preflight

llm_budget:
  stage: preflight
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
    - curl -LO https://github.com/Rul1an/llm-cost/releases/latest/download/llm-cost-linux-x86_64
    - chmod +x llm-cost-linux-x86_64
    - mv llm-cost-linux-x86_64 /usr/local/bin/llm-cost
  script:
    - echo "Checking prompt costs..."
    # Example: Check a JSONL dataset for excessive token usage (> 1M tokens)
    # Note: --max-tokens will cause a non-zero exit code (job failure) if exceeded.
    - cat my_dataset.jsonl | llm-cost pipe --model openai/gpt-4o --summary --max-tokens 1000000
