# SLSA Level 2 Release Workflow
#
# This workflow builds, signs, and releases llm-cost with full supply chain security.
#
# Security features:
# - SBOM generation (CycloneDX via Syft)
# - Keyless signing (Cosign via Sigstore OIDC)
# - Provenance attestation (GitHub Attestations)
# - Checksum verification (SHA256)

name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (no release creation)'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: write       # Create releases, upload assets
  id-token: write       # OIDC token for keyless signing
  attestations: write   # GitHub Attestations API

env:
  ZIG_VERSION: "0.14.0"

jobs:
  # ============================================================================
  # Pre-flight checks
  # ============================================================================
  preflight:
    name: Pre-flight Checks
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      is_prerelease: ${{ steps.version.outputs.is_prerelease }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Version
        id: version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION="${{ github.ref_name }}"
          else
            VERSION="v0.0.0-dev"
          fi
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
          # Check if prerelease (contains - like v1.0.0-rc1)
          if [[ "$VERSION" == *"-"* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi
          
          echo "Version: $VERSION"

      - name: Verify Tag Matches Code Version
        run: |
          # Extract version from source (adjust path as needed)
          CODE_VERSION=$(grep -oP 'version\s*=\s*"\K[^"]+' src/main.zig || echo "unknown")
          TAG_VERSION="${{ steps.version.outputs.version }}"
          
          echo "Code version: $CODE_VERSION"
          echo "Tag version: $TAG_VERSION"
          
          # Skip check for dev builds
          if [[ "$TAG_VERSION" != "v0.0.0-dev" ]]; then
            if [[ "v$CODE_VERSION" != "$TAG_VERSION" ]]; then
              echo "::warning::Version mismatch: code=$CODE_VERSION, tag=$TAG_VERSION"
            fi
          fi

  # ============================================================================
  # Build Matrix
  # ============================================================================
  build:
    name: Build (${{ matrix.target }})
    needs: preflight
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux builds (from ubuntu)
          - os: ubuntu-latest
            target: x86_64-linux-musl
            artifact: llm-cost-linux-x86_64
            binary: llm-cost
            can_sbom: true
            can_sign: true
          
          - os: ubuntu-latest
            target: aarch64-linux-musl
            artifact: llm-cost-linux-arm64
            binary: llm-cost
            can_sbom: true
            can_sign: true
          
          # Windows build (from ubuntu via cross-compile)
          - os: ubuntu-latest
            target: x86_64-windows-gnu
            artifact: llm-cost-windows-x86_64.exe
            binary: llm-cost.exe
            can_sbom: true
            can_sign: true
          
          # macOS builds (native)
          - os: macos-latest
            target: aarch64-macos
            artifact: llm-cost-macos-arm64
            binary: llm-cost
            can_sbom: false  # Syft has issues on macOS
            can_sign: false  # Cosign OIDC requires Linux
          
          - os: macos-latest
            target: x86_64-macos
            artifact: llm-cost-macos-x86_64
            binary: llm-cost
            can_sbom: false
            can_sign: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Build
        run: |
          zig build -Doptimize=ReleaseFast -Dtarget=${{ matrix.target }}
          
          # Verify binary exists
          if [ ! -f "zig-out/bin/${{ matrix.binary }}" ]; then
            echo "::error::Build failed: binary not found"
            exit 1
          fi
          
          # Stage artifact
          mkdir -p dist
          cp "zig-out/bin/${{ matrix.binary }}" "dist/${{ matrix.artifact }}"
          
          # Show binary info
          file "dist/${{ matrix.artifact }}"
          ls -lh "dist/${{ matrix.artifact }}"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.artifact }}
          path: dist/${{ matrix.artifact }}
          if-no-files-found: error
          retention-days: 1

  # ============================================================================
  # Generate SBOM
  # ============================================================================
  sbom:
    name: SBOM (${{ matrix.artifact }})
    needs: build
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - artifact: llm-cost-linux-x86_64
          - artifact: llm-cost-linux-arm64
          - artifact: llm-cost-windows-x86_64.exe

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-${{ matrix.artifact }}
          path: dist/

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0

      - name: Generate SBOM
        run: |
          syft scan "file:dist/${{ matrix.artifact }}" \
            -o cyclonedx-json \
            --catalogers binary \
            > "dist/${{ matrix.artifact }}.cdx.json"
          
          echo "SBOM generated:"
          head -50 "dist/${{ matrix.artifact }}.cdx.json"

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ matrix.artifact }}
          path: dist/${{ matrix.artifact }}.cdx.json
          retention-days: 1

  # ============================================================================
  # Sign Artifacts
  # ============================================================================
  sign:
    name: Sign (${{ matrix.artifact }})
    needs: build
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - artifact: llm-cost-linux-x86_64
          - artifact: llm-cost-linux-arm64
          - artifact: llm-cost-windows-x86_64.exe

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-${{ matrix.artifact }}
          path: dist/

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign with Cosign (Keyless OIDC)
        run: |
          cosign sign-blob \
            --yes \
            --output-signature "dist/${{ matrix.artifact }}.sig" \
            --output-certificate "dist/${{ matrix.artifact }}.crt" \
            "dist/${{ matrix.artifact }}"
          
          echo "Signature created:"
          cat "dist/${{ matrix.artifact }}.sig"
          echo ""
          echo "Certificate:"
          openssl x509 -in "dist/${{ matrix.artifact }}.crt" -text -noout | head -30

      - name: Upload Signature
        uses: actions/upload-artifact@v4
        with:
          name: sig-${{ matrix.artifact }}
          path: |
            dist/${{ matrix.artifact }}.sig
            dist/${{ matrix.artifact }}.crt
          retention-days: 1

  # ============================================================================
  # Generate Provenance Attestation
  # ============================================================================
  attest:
    name: Attest (${{ matrix.artifact }})
    needs: build
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - artifact: llm-cost-linux-x86_64
          - artifact: llm-cost-linux-arm64
          - artifact: llm-cost-windows-x86_64.exe
          - artifact: llm-cost-macos-arm64
          - artifact: llm-cost-macos-x86_64

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-${{ matrix.artifact }}
          path: dist/

      - name: Generate Attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: dist/${{ matrix.artifact }}

  # ============================================================================
  # Create Release
  # ============================================================================
  release:
    name: Create Release
    needs: [preflight, build, sbom, sign, attest]
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.dry_run != 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download All Build Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: build-*
          path: artifacts/builds/
          merge-multiple: true

      - name: Download All SBOMs
        uses: actions/download-artifact@v4
        with:
          pattern: sbom-*
          path: artifacts/sboms/
          merge-multiple: true

      - name: Download All Signatures
        uses: actions/download-artifact@v4
        with:
          pattern: sig-*
          path: artifacts/sigs/
          merge-multiple: true

      - name: Prepare Release Assets
        run: |
          mkdir -p release
          
          # Copy all artifacts
          cp artifacts/builds/* release/ 2>/dev/null || true
          cp artifacts/sboms/* release/ 2>/dev/null || true
          cp artifacts/sigs/* release/ 2>/dev/null || true
          
          # Generate checksums
          cd release
          sha256sum * > SHA256SUMS.txt
          
          echo "Release assets:"
          ls -la

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.preflight.outputs.version }}
          name: llm-cost ${{ needs.preflight.outputs.version }}
          prerelease: ${{ needs.preflight.outputs.is_prerelease }}
          generate_release_notes: true
          files: release/*
          body: |
            ## Installation
            
            ```bash
            # Linux (x86_64)
            curl -LO https://github.com/${{ github.repository }}/releases/download/${{ needs.preflight.outputs.version }}/llm-cost-linux-x86_64
            chmod +x llm-cost-linux-x86_64
            
            # Verify before use
            gh attestation verify llm-cost-linux-x86_64 --repo ${{ github.repository }}
            ```
            
            ## Security
            
            All artifacts are signed and include SLSA Build Level 2 provenance.
            
            ### Verify with GitHub CLI
            ```bash
            gh attestation verify <artifact> --repo ${{ github.repository }}
            ```
            
            ### Verify with Cosign
            ```bash
            cosign verify-blob \
              --signature <artifact>.sig \
              --certificate <artifact>.crt \
              --certificate-identity-regexp "https://github.com/${{ github.repository }}" \
              --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
              <artifact>
            ```
            
            ### SBOM
            Each binary has a CycloneDX SBOM (`.cdx.json`) listing all components.
            
            ## Checksums
            
            See `SHA256SUMS.txt` for file checksums.

  # ============================================================================
  # Post-Release Verification
  # ============================================================================
  verify:
    name: Verify Release
    needs: [preflight, release]
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.dry_run != 'true' }}

    steps:
      - name: Wait for Release Propagation
        run: sleep 30

      - name: Download Release Artifact
        run: |
          curl -fsSL -o llm-cost-linux-x86_64 \
            "https://github.com/${{ github.repository }}/releases/download/${{ needs.preflight.outputs.version }}/llm-cost-linux-x86_64"

      - name: Verify Attestation
        run: |
          gh attestation verify llm-cost-linux-x86_64 --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Smoke Test
        run: |
          chmod +x llm-cost-linux-x86_64
          ./llm-cost-linux-x86_64 --version
          ./llm-cost-linux-x86_64 --help
