const std = @import("std");
const join = @import("join.zig");
const agg = @import("aggregate.zig");
const stats = @import("stats.zig");

pub const Metadata = struct {
    tool_version: []const u8,
    estimates_sha256: []const u8,
    actuals_sha256: []const u8,
    generated_at: ?i64,
    // v1.2.1+ extras
    match_mode: []const u8,
    matched_rows: u64,
    unmatched_actuals: u64,
    unmatched_estimates: u64,
};

pub fn writeToml(allocator: std.mem.Allocator, writer: anytype, result: join.JoinResult, meta: Metadata) !void {
    // Write Metadata
    try writer.print("[metadata]\n", .{});
    try writer.print("schema_version = 1\n", .{});
    try writer.print("tool_version = \"{s}\"\n", .{meta.tool_version});
    try writer.print("match_mode = \"{s}\"\n", .{meta.match_mode});

    try writer.print("\n[metadata.lineage]\n", .{});
    try writer.print("estimates_sha256 = \"{s}\"\n", .{meta.estimates_sha256});
    try writer.print("actuals_sha256 = \"{s}\"\n", .{meta.actuals_sha256});

    if (meta.generated_at) |ts| {
        try writer.print("generated_at = {d}\n", .{ts});
    }

    try writer.print("\n[metadata.stats]\n", .{});
    try writer.print("matched_rows = {d}\n", .{meta.matched_rows});
    try writer.print("unmatched_actuals = {d}\n", .{meta.unmatched_actuals});
    try writer.print("unmatched_estimates = {d}\n", .{meta.unmatched_estimates});

    try writer.print("\n", .{});

    try writer.print("# generated by llm-cost calibrate\n", .{});
    try writer.print("# comparisons: {d} matched, {d} unmatched actuals\n\n", .{
        result.stats.matched_rows,
        result.stats.unmatched_actuals,
    });

    var it = result.groups.iterator();
    var keys = std.ArrayList(agg.GroupKey).init(allocator);
    defer keys.deinit();

    while (it.next()) |entry| {
        try keys.append(entry.key_ptr.*);
    }

    std.mem.sort(agg.GroupKey, keys.items, {}, groupLessThan);

    for (keys.items) |key| {
        const ag = result.groups.get(key).?;
        const ratio_opt = ag.multiplierRatio();

        if (ratio_opt) |r| {
            const drift = stats.driftFromRatio(r);
            const confidence = if (ag.n_rows > 100) "high" else if (ag.n_rows > 10) "medium" else "low";

            // Multiplier float for TOML
            // ratio = num/den
            std.debug.assert(ag.sum_est_micro != 0);
            const multiplier = @as(f64, @floatFromInt(ag.sum_act_micro)) / @as(f64, @floatFromInt(ag.sum_est_micro));

            try writer.print("[[factor]]\n", .{});
            try writer.print("model = \"{s}\"\n", .{key.model});
            if (key.scenario.len > 0) {
                try writer.print("scenario = \"{s}\"\n", .{key.scenario});
            }
            try writer.print("multiplier = {d:.4}\n", .{multiplier});
            try writer.print("drift_bps = {d}\n", .{drift.drift_bps});
            try writer.print("confidence = \"{s}\"\n", .{confidence});
            try writer.print("samples = {d}\n", .{ag.n_rows});
            try writer.print("\n", .{});
        }
    }
}

fn groupLessThan(_: void, a: agg.GroupKey, b: agg.GroupKey) bool {
    const cmp_model = std.mem.order(u8, a.model, b.model);
    if (cmp_model != .eq) return cmp_model == .lt;
    return std.mem.order(u8, a.scenario, b.scenario) == .lt;
}
