const std = @import("std");
const join = @import("join.zig");
const agg = @import("aggregate.zig");
const stats = @import("stats.zig");

pub fn writeToml(allocator: std.mem.Allocator, writer: anytype, result: join.JoinResult) !void {
    try writer.print("# generated by llm-cost calibrate\n", .{});
    try writer.print("# comparisons: {d} matched, {d} unmatched actuals\n\n", .{
        result.stats.matched_rows,
        result.stats.unmatched_actuals,
    });

    var it = result.groups.iterator();

    // Sort keys for deterministic output?
    // HashMap iterator is random-ish ( implementation defined order).
    // We should collect and sort by model/scenario.

    // ... For now, just iterate (User asked for Deterministic TOML).
    // We MUST sort.

    var keys = std.ArrayList(agg.GroupKey).init(allocator);
    defer keys.deinit();

    while (it.next()) |entry| {
        try keys.append(entry.key_ptr.*);
    }

    std.mem.sort(agg.GroupKey, keys.items, {}, groupLessThan);

    for (keys.items) |key| {
        const ag = result.groups.get(key).?;
        const ratio_opt = ag.multiplierRatio();

        if (ratio_opt) |r| {
            const drift = stats.driftFromRatio(r);

            // Heuristic confidence based on observation count (proxy for statistical significance of the mean)
            // Ideally we'd use variance, but N is a good proxy for "should we trust this?"
            const confidence = if (ag.n_rows > 100) "high" else if (ag.n_rows > 10) "medium" else "low";

            // Multiplier float for TOML
            // ratio = num/den
            std.debug.assert(ag.sum_est_micro != 0);
            const multiplier = @as(f64, @floatFromInt(ag.sum_act_micro)) / @as(f64, @floatFromInt(ag.sum_est_micro));

            try writer.print("[[factor]]\n", .{});
            try writer.print("model = \"{s}\"\n", .{key.model});
            try writer.print("scenario = \"{s}\"\n", .{key.scenario});
            try writer.print("multiplier = {d:.4}\n", .{multiplier});
            try writer.print("drift_bps = {d}\n", .{drift.drift_bps});
            try writer.print("confidence = \"{s}\"\n", .{confidence});
            try writer.print("samples = {d}\n", .{ag.n_rows});
            try writer.print("\n", .{});
        }
    }
}

fn groupLessThan(_: void, a: agg.GroupKey, b: agg.GroupKey) bool {
    const cmp_model = std.mem.order(u8, a.model, b.model);
    if (cmp_model != .eq) return cmp_model == .lt;
    return std.mem.order(u8, a.scenario, b.scenario) == .lt;
}
